// Projects data
export const projects = [
  {
    name: "BNRY BNB Bridge",
    handle: "binarybridge",
    url: "https://platform.binarybit.pro",
    images: ["/src/assets/bnry.GIF"],
    description: [
      "implemented bridge platform",
      "added smart contracts",
      "integrated bnb network",
      "swap bnry to bsc feature",
    ],
    techStack: [
      { name: "crepcrypto", iconImage: "/src/assets/crep.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
      { name: "System", iconImage: "/src/assets/system.png" },
      { name: "Mongo", iconImage: "/src/assets/mongo.png" },
    ],
  },
  {
    name: "The wisetrade",
    handle: "thewisetrade",
    url: "https://thewisetrade.io",
    images: ["/src/assets/wisetrade.GIF"],
    description: [
      "implemented frontend with vue.js",
      "added DLMM active pool",
      "implemented meteora open positions",
      "DLMM performance tracking",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "js", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Vue.js", iconImage: "/src/assets/vue.svg" },
    ],
  },
  {
    name: "404.fun",
    handle: "404.fun",
    url: "https://404.fun",
    images: ["/src/assets/404.webp"],
    description: [
      "implemented frontend with next.js",
      "integrate chatbot with openai",
      "integrated next.js to wix for hosting",
    ],
    techStack: [
      { name: "asterisk", iconImage: "/src/assets/asterisk.png" },
      { name: "js", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "System", iconImage: "/src/assets/system.png" },
    ],
  },
  {
    name: "koasync",
    handle: "koasync",
    url: "https://koasync.com",
    images: ["/src/assets/koa.webp"],
    description: [
      "implemented frontend with next.js",
      "integrate chatbot with openai",
      "integrated next.js to wix for hosting",
    ],
    techStack: [
      { name: "chat-gpt", iconImage: "/src/assets/chat-gpt.png" },
      { name: "js", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "fatcatdao",
    handle: "fatcatdao",
    url: "https://fatcatdao.io/#team",
    images: ["/src/assets/fatcat.webp"],
    description: [
      "design website using figma",
      "built frontend with next.js",
      "setup candymachine for minting",
      "integrated web3 data",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "js", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "tech-stack-2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "hypedotfun",
    handle: "hypedotfun",
    url: "https://hype.fun",
    images: ["/src/assets/hype.webp"],
    description: [
      "implemented frontend",
      " built launchpad smart contract with rust",
      "integrated web3 data with backend",
      "backend with node & ts",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "js", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Vue.js", iconImage: "/src/assets/vue.svg" },
    ],
  },
  {
    name: "Chainswap",
    handle: "Chainswap",
    url: "https://www.chainswap.tech",
    images: ["/src/assets/chainswap.gif"],
    description: [
      "implemented cctp v2",
      "make faster exec, deeper liquidity",
      "integrated cross-chain protocols",
      "ccip complete chains on cross chainswap",
    ],
    techStack: [
      { name: "Tech Stack 1", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "Tech Stack 4", iconImage: "/src/assets/tech-stack-4.png" },
      { name: "Bitcoin", iconImage: "/src/assets/bitcoin.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "AMANA Defi",
    handle: "AMANA Defi",
    url: "https://amanadefi.com",
    images: ["/src/assets/amana.webp"],
    description: [
      "cross-chain lending&borrowing aggr protocol",
      "frontend with nextJS with the fashionable design",
      "Integrated the gateway contracts on zetachain",
      "deployed the sc to integrate with the gateway contract",
      "Collaborated with thirdWeb&zetachain team to support the multi-chain including solana",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "Tech Stack 4", iconImage: "/src/assets/tech-stack-4.png" },
      { name: "TypeScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 3", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "Bitmap Community",
    handle: "Bitmap Community",
    url: "https://bitmap.community",
    images: ["/src/assets/bitmap.gif"],
    description: [
      "built nodejs backend for inscribing service",
      "reinscription, parent/child provenance, delegate, file/text(bulk text for batch inscriptions) inscribing",
      "used bitcoinjs-lib, tx fee optimization",
      "used native-segwit/taproot address compatible, api rate limit distributing",
    ],
    techStack: [
      { name: "Bitcoin", iconImage: "/src/assets/bitcoin.png" },
      { name: "TypeScript", iconImage: "/src/assets/js.png" },
      { name: "Mongo", iconImage: "/src/assets/mongo.png" },
      { name: "Tech Stack 3", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "DASHCOIN",
    handle: "DASHCOIN",
    url: "https://dashcoin.meme",
    images: ["/src/assets/dashcoin.webp"],
    description: [
      "implemented frontend with t3 stack",
      "integrated dune api",
      "mongodb as dmbs, node backend",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "TypeScript", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "Memepad Launchpad",
    handle: "Memepad Launchpad",
    url: "https://memepad.ai",
    images: ["/src/assets/memepad.webp"],
    description: [
      "implemented token smart contracts",
      "integrate sc with meteora",
      "reward system for token holders",
      "staking rewards for token holders",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Rust", iconImage: "/src/assets/rust.png" },
    ],
  },
  {
    name: "Fork Trojanbot SOL",
    handle: "Fork Trojanbot SOL",
    url: "https://t.me/trojanusrobot",
    images: ["/src/assets/trojan.webp"],
    description: [
      "instant&automated trade logic implement",
      "rapid exec with bolt tech",
      "protect mev via jito slots",
      "add limit orders& DCA strategies",
    ],
    techStack: [
      { name: "telegram", iconImage: "/src/assets/telegram.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
    ],
  },
  {
    name: "Solana Whale Tracker",
    handle: "Solana Whale Tracker",
    url: "https://wallet-tracking-app.vercel.app",
    images: ["/src/assets/whaletracker.gif"],
    description: [
      "implemented frontend with t3 stack",
      "added wallet tracking api(birdeye, dexscreener api)",
      "integrated twitter notifications",
    ],
    techStack: [
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
      { name: "Twitter", iconImage: "/src/assets/twitter.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Tech Stack 1", iconImage: "/src/assets/tech-stack-1.png" },
    ],
  },
  {
    name: "SocialAI frontend development",
    handle: "SocialAI frontend development",
    url: "https://social-ai-fe.vercel.app",
    images: ["/src/assets/socialai.gif"],
    description: [
      "implemented frontend with next.js",
      "material ui + shadcn ui",
      "integrated tailwind css",
      "deployed on vercel",
    ],
    techStack: [
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
      { name: "Tailwind", iconImage: "/src/assets/tailwind.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
    ],
  },
  {
    name: "Telegram Chatbot",
    handle: "Telegram Chatbot",
    url: "https://t.me/RoboAceBot",
    images: ["/src/assets/aichat.webp"],
    description: [
      "implemented telegram bot",
      "added chatgpt integration with api",
      "integrated browserless api for scraping",
      "ask my bot anything 24/7",
    ],
    techStack: [
      { name: "chat-gpt", iconImage: "/src/assets/chat-gpt.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "Pumpfun Fork",
    handle: "Pumpfun Fork",
    url: "https://pumpfun-eta.vercel.app",
    images: ["/src/assets/pumpfun.gif"],
    description: [
      "forked pumpfun frontend",
      "backend with node & ts",
      "bunding curve logic",
      "solana web3 integration",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "TypeScript", iconImage: "/src/assets/tech-stack-3.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Mongo", iconImage: "/src/assets/mongo.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },

    ],
  },
  {
    name: "Jeff Token Website",
    handle: "Jeff Token Website",
    url: "https://www.jeffreysol.xyz",
    images: ["/src/assets/icypopo.gif"],
    description: [
      "implemented frontend",
      "high level anime windowsxp theme",
      "deployed website",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "$PUGGY Token Website",
    handle: "$PUGGY Token Website",
    url: "https://www.pugclub.xyz",
    images: ["/src/assets/pug.gif"],
    description: [
      "implemented frontend with next.js",
      "integrated ca wallet",
      "deployed website",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
      { name: "Tailwind", iconImage: "/src/assets/tailwind.png" },
    ],
  },
  {
    name: "$Popo Token Website",
    handle: "$Popo Token Website",
    url: "https://icypopo.xyz",
    images: ["/src/assets/popo.gif"],
    description: [
      "implemented frontend",
      "integrated solana wallet",
      "deployed website",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
      { name: "Tailwind", iconImage: "/src/assets/tailwind.png" },
    ],
  },
  {
    name: "Shurk Token Website",
    handle: "Shurk Token Website",
    url: "https://www.shurkysheen.com",
    images: ["/src/assets/shurk.gif"],
    description: [
      "implemented frontend",
      "added smart contracts",
      "integrated solana wallet",
      "deployed website",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
      { name: "Tailwind", iconImage: "/src/assets/tailwind.png" },
    ],
  },
  {
    name: "Ordinal Swap",
    handle: "Ordinal Swap",
    url: "https://munchswap.xyz",
    images: ["/src/assets/shurk.gif"],
    description: [
      "swap ordinal assets",
      "integrated bitcoin wallets",
      "add multiswap for ordinal tokens",
    ],
    techStack: [
      { name: "Bitcoin", iconImage: "/src/assets/bitcoin.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "Wooshi World",
    handle: "Wooshi World",
    url: "https://wooshi.world",
    images: ["/src/assets/project-6.webp"],
    description: [
      "modified shopify components",
      "added web3 functions",
      "integrated social media track system",
      "integrated solana wallet",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "Tech Stack 2", iconImage: "/src/assets/tech-stack-2.png" },
    ],
  },
  {
    name: "Solana Token Launchpad",
    handle: "Solana Token Launchpad",
    url: "https://miragelaunchpad.xyz",
    images: ["/src/assets/launchpad.webp"],
    description: [
      "implemented frontend",
      "added token creation api",
      "integrated raydium&jupiter api",
      "deployed smart contracts",
    ],
    techStack: [
      { name: "Node.js", iconImage: "/src/assets/tech-stack-1.png" },
      { name: "JavaScript", iconImage: "/src/assets/js.png" },
      { name: "React", iconImage: "/src/assets/react.png" },
      { name: "Mongo", iconImage: "/src/assets/mongo.png" },
    ],
  },
  {
    name: "Carefizz",
    handle: "Carefizz",
    url: "https://lv.carefizz.com",
    images: ["/src/assets/project-28.webp"],
    description: [
      "implemented frontend with nuxt",
      "added management system",
      "integrated mevn stack",
      "deployed website with netlify",
    ],
    techStack: [
      { name: "Tailwind", iconImage: "/src/assets/tailwind.png" },
      { name: "Vue.js", iconImage: "/src/assets/vue.svg" },
    ],
  },
];
